default: &default
  adapter: postgresql
  encoding: unicode
  pool: 20
  host: localhost

development:
  <<: *default
  database: aladin
  username: postgres
  password: shved

test:
  <<: *default
  database: aladin
  username: postgres
  password: shved
